//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.03.07 at 08:01:26 PM CET 
//


package org.mytvstream.configuration;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="client">
 *           &lt;complexType>
 *             &lt;simpleContent>
 *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *                 &lt;attribute name="type" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="producerserver" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/extension>
 *             &lt;/simpleContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="backends">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="backend" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="server" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="port" type="{http://www.w3.org/2001/XMLSchema}short"/>
 *                             &lt;element name="httpport" type="{http://www.w3.org/2001/XMLSchema}short"/>
 *                             &lt;element name="usernmame" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="password" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                           &lt;/sequence>
 *                           &lt;attribute name="type" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "client",
    "backends"
})
@XmlRootElement(name = "configuration")
public class Configuration {

    @XmlElement(required = true)
    protected Configuration.Client client;
    @XmlElement(required = true)
    protected Configuration.Backends backends;

    /**
     * Gets the value of the client property.
     * 
     * @return
     *     possible object is
     *     {@link Configuration.Client }
     *     
     */
    public Configuration.Client getClient() {
        return client;
    }

    /**
     * Sets the value of the client property.
     * 
     * @param value
     *     allowed object is
     *     {@link Configuration.Client }
     *     
     */
    public void setClient(Configuration.Client value) {
        this.client = value;
    }

    /**
     * Gets the value of the backends property.
     * 
     * @return
     *     possible object is
     *     {@link Configuration.Backends }
     *     
     */
    public Configuration.Backends getBackends() {
        return backends;
    }

    /**
     * Sets the value of the backends property.
     * 
     * @param value
     *     allowed object is
     *     {@link Configuration.Backends }
     *     
     */
    public void setBackends(Configuration.Backends value) {
        this.backends = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="backend" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="server" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="port" type="{http://www.w3.org/2001/XMLSchema}short"/>
     *                   &lt;element name="httpport" type="{http://www.w3.org/2001/XMLSchema}short"/>
     *                   &lt;element name="usernmame" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="password" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                 &lt;/sequence>
     *                 &lt;attribute name="type" type="{http://www.w3.org/2001/XMLSchema}string" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "backend"
    })
    public static class Backends {

        protected List<Configuration.Backends.Backend> backend;

        /**
         * Gets the value of the backend property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the backend property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getBackend().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Configuration.Backends.Backend }
         * 
         * 
         */
        public List<Configuration.Backends.Backend> getBackend() {
            if (backend == null) {
                backend = new ArrayList<Configuration.Backends.Backend>();
            }
            return this.backend;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="server" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="port" type="{http://www.w3.org/2001/XMLSchema}short"/>
         *         &lt;element name="httpport" type="{http://www.w3.org/2001/XMLSchema}short"/>
         *         &lt;element name="usernmame" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="password" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *       &lt;/sequence>
         *       &lt;attribute name="type" type="{http://www.w3.org/2001/XMLSchema}string" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "server",
            "port",
            "httpport",
            "usernmame",
            "password"
        })
        public static class Backend {

            @XmlElement(required = true)
            protected String server;
            protected short port;
            protected short httpport;
            @XmlElement(required = true)
            protected String usernmame;
            @XmlElement(required = true)
            protected String password;
            @XmlAttribute
            protected String type;

            /**
             * Gets the value of the server property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getServer() {
                return server;
            }

            /**
             * Sets the value of the server property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setServer(String value) {
                this.server = value;
            }

            /**
             * Gets the value of the port property.
             * 
             */
            public short getPort() {
                return port;
            }

            /**
             * Sets the value of the port property.
             * 
             */
            public void setPort(short value) {
                this.port = value;
            }

            /**
             * Gets the value of the httpport property.
             * 
             */
            public short getHttpport() {
                return httpport;
            }

            /**
             * Sets the value of the httpport property.
             * 
             */
            public void setHttpport(short value) {
                this.httpport = value;
            }

            /**
             * Gets the value of the usernmame property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getUsernmame() {
                return usernmame;
            }

            /**
             * Sets the value of the usernmame property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setUsernmame(String value) {
                this.usernmame = value;
            }

            /**
             * Gets the value of the password property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getPassword() {
                return password;
            }

            /**
             * Sets the value of the password property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setPassword(String value) {
                this.password = value;
            }

            /**
             * Gets the value of the type property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getType() {
                return type;
            }

            /**
             * Sets the value of the type property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setType(String value) {
                this.type = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;simpleContent>
     *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
     *       &lt;attribute name="type" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="producerserver" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     &lt;/extension>
     *   &lt;/simpleContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "value"
    })
    public static class Client {

        @XmlValue
        protected String value;
        @XmlAttribute
        protected String type;
        @XmlAttribute
        protected String producerserver;

        /**
         * Gets the value of the value property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setValue(String value) {
            this.value = value;
        }

        /**
         * Gets the value of the type property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getType() {
            return type;
        }

        /**
         * Sets the value of the type property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setType(String value) {
            this.type = value;
        }

        /**
         * Gets the value of the producerserver property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getProducerserver() {
            return producerserver;
        }

        /**
         * Sets the value of the producerserver property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setProducerserver(String value) {
            this.producerserver = value;
        }

    }

}
